[features]
seeds = false
[programs.devnet]
agreement = "7Axu4X13PPv9gKnqDUwZVpF7R3dwwWJvZVJo7Rgt2oWW"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/forgets_code/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
